### ISSUE TITLE
The example workflow fails during update-index

### ISSUE THREAD

**Issue by muesli** [arduino/actions#10]
Run arduino-cli core update-index
Error initializing package manager: cannot initialize package manager: loading hardware packages: loading hardware from C:\Users\runneradmin\AppData\Local\Arduino15\packages: C:\Users\runneradmin\AppData\Local\Arduino15\packages is not a directory
Error initializing package manager: cannot initialize package manager: loading hardware packages: loading hardware from C:\Users\runneradmin\AppData\Local\Arduino15\packages: C:\Users\runneradmin\AppData\Local\Arduino15\packages is not a directory
##[error]Process completed with exit code 1.

**Comment by per1234** [comment]
This is a bug with arduino-cli: https://github.com/arduino/arduino-cli/issues/529
It has already been fixed in that repository but the issue will remain with the CI builds until a new release is made.

**Comment by per1234** [comment]
arduino-cli 0.7.1 has now been released with https://github.com/arduino/arduino-cli/issues/529 fixed, so this error should no longer occur.

**Comment by muesli** [comment]
Confirmed, thank you!
