### ISSUE TITLE
Workflow Templates

### ISSUE THREAD

**Issue by peternewman** [arduino/actions#62]
This might be interesting:
https://github.blog/2020-06-22-promote-consistency-across-your-organization-with-workflow-templates/

**Comment by per1234** [comment]
@peternewman thanks! That is indeed an interesting feature.

Arduino has an ever increasing number of library repositories that all need very similar workflows. In addition to that, the codespell workflow could be added to even the non-library repositories. It would be very nice to have a single centralized source of base workflows that would be used every time CI is set up on a repo, with, at most, only the need to make some small modifications for project-specific configurations.

**Comment by aentinger** [comment]
Thank you @peternewman for mentioning this :+1: I'm closing this issue as it seems to me that the information transfer has occured and therefore this issue has fulfilled its reason for existence.
